Add two PYLINT warnings
Error: PYLINT_WARNING:
python/hello-world-python:1: C0114[missing-module-docstring]: Missing module docstring

Error: PYLINT_WARNING:
python/hello-world-python:4: C0116[missing-function-docstring]: api_method: Missing function or method docstring